# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PYTHON\PySeer\ui\create_new_file_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateNewFile(object):
    def setupUi(self, CreateNewFile):
        CreateNewFile.setObjectName("CreateNewFile")
        CreateNewFile.resize(320, 240)
        CreateNewFile.setMinimumSize(QtCore.QSize(320, 240))
        CreateNewFile.setMaximumSize(QtCore.QSize(320, 240))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        CreateNewFile.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(CreateNewFile)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 261, 122))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_4.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.pushButton_5 = QtWidgets.QPushButton(CreateNewFile)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 210, 81, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(CreateNewFile)
        self.pushButton.setGeometry(QtCore.QRect(130, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget1 = QtWidgets.QWidget(CreateNewFile)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 10, 251, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)

        self.retranslateUi(CreateNewFile)
        self.pushButton_2.clicked.connect(CreateNewFile.btn_clicked_2)
        self.pushButton_1.clicked.connect(CreateNewFile.btn_clicked_1)
        self.lineEdit.textChanged['QString'].connect(CreateNewFile.get_windowname)
        self.pushButton.clicked.connect(CreateNewFile.grab_window)
        self.pushButton_3.clicked.connect(CreateNewFile.btn_clicked_3)
        self.pushButton_4.clicked.connect(CreateNewFile.btn_clicked_4)
        self.pushButton_5.clicked.connect(CreateNewFile.btn_clicked_5)
        QtCore.QMetaObject.connectSlotsByName(CreateNewFile)

    def retranslateUi(self, CreateNewFile):
        _translate = QtCore.QCoreApplication.translate
        CreateNewFile.setWindowTitle(_translate("CreateNewFile", "Form"))
        self.pushButton_1.setText(_translate("CreateNewFile", "添加目标"))
        self.pushButton_2.setText(_translate("CreateNewFile", "添加目标【循环开始】"))
        self.pushButton_3.setText(_translate("CreateNewFile", "添加目标【循环中】"))
        self.pushButton_4.setText(_translate("CreateNewFile", "添加目标【循环结束】"))
        self.pushButton_5.setText(_translate("CreateNewFile", "完成"))
        self.pushButton.setText(_translate("CreateNewFile", "获取屏幕"))
        self.label.setText(_translate("CreateNewFile", "窗口名："))
