# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PYTHON\PySeer\ui\create_new_file_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateNewFile(object):
    def setupUi(self, CreateNewFile):
        CreateNewFile.setObjectName("CreateNewFile")
        CreateNewFile.resize(320, 240)
        CreateNewFile.setMinimumSize(QtCore.QSize(320, 240))
        CreateNewFile.setMaximumSize(QtCore.QSize(320, 240))
        self.centralwidget = QtWidgets.QWidget(CreateNewFile)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 272, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 50, 301, 126))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_4.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        CreateNewFile.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateNewFile)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 23))
        self.menubar.setObjectName("menubar")
        CreateNewFile.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateNewFile)
        self.statusbar.setObjectName("statusbar")
        CreateNewFile.setStatusBar(self.statusbar)

        self.retranslateUi(CreateNewFile)
        self.lineEdit.textChanged['QString'].connect(CreateNewFile.get_windowname)
        self.pushButton.clicked.connect(CreateNewFile.grab_window)
        self.pushButton_4.clicked.connect(CreateNewFile.btn_clicked_4)
        self.pushButton_5.clicked.connect(CreateNewFile.btn_clicked_5)
        self.pushButton_3.clicked.connect(CreateNewFile.btn_clicked_3)
        self.pushButton_2.clicked.connect(CreateNewFile.btn_clicked_2)
        self.pushButton_1.clicked.connect(CreateNewFile.btn_clicked_1)
        QtCore.QMetaObject.connectSlotsByName(CreateNewFile)

    def retranslateUi(self, CreateNewFile):
        _translate = QtCore.QCoreApplication.translate
        CreateNewFile.setWindowTitle(_translate("CreateNewFile", "MainWindow"))
        self.label.setText(_translate("CreateNewFile", "窗口名："))
        self.pushButton.setText(_translate("CreateNewFile", "获取屏幕"))
        self.pushButton_1.setText(_translate("CreateNewFile", "添加目标"))
        self.pushButton_2.setText(_translate("CreateNewFile", "添加目标【循环开始】"))
        self.pushButton_3.setText(_translate("CreateNewFile", "添加目标【循环结束】"))
        self.pushButton_5.setText(_translate("CreateNewFile", "撤销"))
        self.pushButton_4.setText(_translate("CreateNewFile", "完成"))
