# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PYTHON\PySeer\ui\create_new_file_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateNewFile(object):
    def setupUi(self, CreateNewFile):
        CreateNewFile.setObjectName("CreateNewFile")
        CreateNewFile.resize(320, 240)
        CreateNewFile.setMinimumSize(QtCore.QSize(320, 240))
        CreateNewFile.setMaximumSize(QtCore.QSize(320, 240))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        CreateNewFile.setFont(font)
        self.widget = QtWidgets.QWidget(CreateNewFile)
        self.widget.setGeometry(QtCore.QRect(50, 80, 219, 64))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CreateNewFile)
        self.pushButton_1.clicked.connect(CreateNewFile.btn_clicked_1)
        self.pushButton_3.clicked.connect(CreateNewFile.btn_clicked_2)
        QtCore.QMetaObject.connectSlotsByName(CreateNewFile)

    def retranslateUi(self, CreateNewFile):
        _translate = QtCore.QCoreApplication.translate
        CreateNewFile.setWindowTitle(_translate("CreateNewFile", "Dialog"))
        self.label.setText(_translate("CreateNewFile", "本次循环次数"))
        self.pushButton_1.setText(_translate("CreateNewFile", "保存"))
        self.pushButton_3.setText(_translate("CreateNewFile", "取消"))
