# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PYTHON\PySeer\ui\create_new_file_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateNewFile(object):
    def setupUi(self, CreateNewFile):
        CreateNewFile.setObjectName("CreateNewFile")
        CreateNewFile.resize(240, 200)
        CreateNewFile.setMinimumSize(QtCore.QSize(240, 200))
        CreateNewFile.setMaximumSize(QtCore.QSize(240, 200))
        self.layoutWidget = QtWidgets.QWidget(CreateNewFile)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 158, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(CreateNewFile)
        self.pushButton.clicked.connect(CreateNewFile.btn_clicked_1)
        self.pushButton_2.clicked.connect(CreateNewFile.btn_clicked_2)
        QtCore.QMetaObject.connectSlotsByName(CreateNewFile)

    def retranslateUi(self, CreateNewFile):
        _translate = QtCore.QCoreApplication.translate
        CreateNewFile.setWindowTitle(_translate("CreateNewFile", "Dialog"))
        self.pushButton.setText(_translate("CreateNewFile", "保存"))
        self.pushButton_2.setText(_translate("CreateNewFile", "取消"))
