# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PYTHON\PySeer\ui\load_file_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadFile(object):
    def setupUi(self, LoadFile):
        LoadFile.setObjectName("LoadFile")
        LoadFile.resize(320, 240)
        LoadFile.setMinimumSize(QtCore.QSize(320, 240))
        LoadFile.setMaximumSize(QtCore.QSize(320, 240))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        LoadFile.setFont(font)
        self.pushButton = QtWidgets.QPushButton(LoadFile)
        self.pushButton.setGeometry(QtCore.QRect(120, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(LoadFile)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 301, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(LoadFile)
        self.lineEdit.textChanged['QString'].connect(LoadFile.update_dbpath)
        self.lineEdit_2.textChanged['QString'].connect(LoadFile.update_windowname)
        self.pushButton.clicked.connect(LoadFile.btn_clicked_1)
        QtCore.QMetaObject.connectSlotsByName(LoadFile)

    def retranslateUi(self, LoadFile):
        _translate = QtCore.QCoreApplication.translate
        LoadFile.setWindowTitle(_translate("LoadFile", "Form"))
        self.pushButton.setText(_translate("LoadFile", "加载"))
        self.label.setText(_translate("LoadFile", "文件路径："))
        self.label_2.setText(_translate("LoadFile", "窗口标题："))
